### ISSUE TITLE
CleaveLand 4.4 - Bowtie dependency problem

### ISSUE THREAD

**Issue by adbsd** [MikeAxtell/CleaveLand4#13]
I see the problem. Newer versions of bowtie have changed their output when the command 'bowtie --version' is run. CleaveLand 4.4 expects a response formatted in a certain way; newer bowtie versions don't conform. It should be an easy fix but might take me a day or two get to it in between other tasks. Thanks for letting me know about it.
 
>I am trying to run an analysis using Cleaveland 4.4 but I am unable to fix a dependency problem linked to Bowtie. Bowtie 1.2.2. is well installed on my Ubuntu machine, bowtie is set in the Path variable and responding on call in the prompt using the “bowtie” command. 
I also tried the 4.3 version of Cleaveland but the same problem of Bowtie dependency appears.
Do you have any idea what could cause this problem and how to solve it?

**Comment by MikeAxtell** [comment]
Thanks again for pointing this out. Release 4.5 fixes this issue.
