### ISSUE TITLE
ABORT: Failed to find length of transcript NULL in hash in sub-routine report_dd

### ISSUE THREAD

**Issue by juancrescente** [MikeAxtell/CleaveLand4#15]
Hello Dr Axtell,

For some reason it is not processing the reads. 

`./CleaveLand4.pl -e $fasta_degradome_1 -u $miRNAs -n $transcriptome -p 0.05`

```
Initiating alignment of degradome reads to transcriptome.
Bowtie index files for /home/juan/Desktop/juan/bio/mrcv/data/res/04_02_19/DEG-cdna.fasta PRESENT
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)
No alignments
Alignments complete. Generating degradome density file.
ABORT: Failed to find length of transcript NULL in hash in sub-routine report_dd
```

I've checked the transcript file and seems ok, a fasta with no whitespaces in header. 

thank you

**Comment by juancrescente** [comment]
seems like I cannot use samtools and bowtie available in bioconda, instead I have to download binaries

**Comment by Andhingr** [comment]
Dear Dr. Axtell

I am facing the same issue. I get the same error: ABORT: Failed to find length of transcript NULL in hash in sub-routine report_dd. 
I am using samtools-1.2 and bowtie-0.12.9 in the binary version (not in bioconda) as specified by the previous user. I also double checked my transcript fasta file, there are no whitespaces in the header. Below is what my transcript file looks like when I head the file. I request you to please suggest what might be causing this error. Thank you.

>XM_016075778.2
CTACCTTCTAGTCTGACCGGTCCATACATAAGGCATCAAGGCAATAGCAATTCTGAGTTCTGAGAATGTTTCCGGCGGGG
GAACTCTCATGGCTTTGCCGCCTAGTCGTCGAGACTCTCAACCCCTACACAGAACCAGACGCCTTCTCTTCAATTTGCAA
ACAGAAGGAGAAGGAGCTTCTACTCGCTTCTTCTCAGGTCGTGAGAAAAATTCAGCTGCGGATTCGAGAGTTCGATTCTC
ATATAGAGAGCACAGCGACGAAACCTGTTCCAAACGACGACGGTTTATTCTGTTCGGACCACCATTTTTCGGCTCATCAA
TGTCTCTCTGCAATTGTAACCAAAATGATGACTTTGCT
