### ISSUE TITLE
Detect alternative slicing sites?

### ISSUE THREAD

**Issue by jonbra** [MikeAxtell/CleaveLand4#17]
I am running CleaveLand on a non-plant organism, and I was thinking to check whether there could be slicing at other positions along the predicted miRNA target site. Would it be easy to tweak the code to search for, lets say, any category zero site in a given GSTAr alignment, and then calcuate the p-values for that site?

Thanks,

Jon

**Comment by MikeAxtell** [comment]
Hi Jon,

I'm not sure. Unfortunately I'm not actively developing CleaveLand4 at the
moment. But it's all perl, go ahead and fork it and see what you can come
up with!

On Tue, May 14, 2019 at 3:58 PM Jon Bråte <notifications@github.com> wrote:

> I am running CleaveLand on a non-plant organism, and I was thinking to
> check whether there could be slicing at other positions along the predicted
> miRNA target site. Would it be easy to tweak the code to search for, lets
> say, any category zero site in a given GSTAr alignment, and then calcuate
> the p-values for that site?
>
> Thanks,
>
> Jon
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeAxtell%2FCleaveLand4%2Fissues%2F17%3Femail_source%3Dnotifications%26email_token%3DABUJPCKVLME7T5TMFKKUKTDPVMKUNA5CNFSM4HM5FSR2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GTYMNOQ&data=02%7C01%7Cmja18%40psu.edu%7C0e3f917c7f8e4fe68ffd08d6d8a677d2%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636934606823488078&sdata=wZXdDHsLdViAKQflcgOfkkkIpf6dLuAjVUIHmdPCBkw%3D&reserved=0>,
> or mute the thread
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABUJPCKW4KRD6E34OFT66S3PVMKUNANCNFSM4HM5FSRQ&data=02%7C01%7Cmja18%40psu.edu%7C0e3f917c7f8e4fe68ffd08d6d8a677d2%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636934606823498087&sdata=B%2FWhBjZdqqqbwL4uoyHkiN2EscMCvboe4b0MOuN1%2BuA%3D&reserved=0>
> .
>


-- 
Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
http://sites.psu.edu/axtell
http://plantsmallrnagenes.science.psu.edu

**Comment by jonbra** [comment]
I see, thanks!
