### ISSUE TITLE
Error in creating bam

### ISSUE THREAD

**Issue by a92932000** [MikeAxtell/CleaveLand4#3]
## Error in creating bam:

CleaveLand4 version 4.3
Tue Mar 29 11:50:58 CST 2016

Mode: 1
Checking Dependencies
        bowtie: PASS version 1.1.2
        bowtie-build: PASS version 1.1.2
        RNAplex: PASS RNAplex 2.2.4
        GSTAr: PASS GSTAr.pl version 1.0
        samtools: PASS Version: 1.3 (using htslib 1.3)
        R: PASS R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"

T-plot directory plots already exists, new T-plots will be placed there.

Initiating alignment of degradome reads to transcriptome.
Bowtie index files for cDNA.fasta PRESENT
Error while flushing and closing output
terminate called after throwing an instance of 'int'
ABORT: No bam file cDNA.fasta_sorted.bam found after bowtie call in sub-routine make_deg_density
## I corrected CleaveLand.pl and CleaveLand work well:

if($opt_q) {
        system "bowtie -f -v 1 --best -k 1 --norc -S $opt_n $opt_e 2> /dev/null | sed -e 's/SO:unsorted/SO:coordinate/' 2> /dev/null | samtools view -S -b -u - 2> /dev/null | samtools sort - $bam_name 2> /dev/null";
    } else {
        system "bowtie -f -v 1 --best -k 1 --norc -S $opt_n $opt_e | sed -e 's/SO:unsorted/SO:coordinate/' | samtools view -S -b -u - 2> /dev/null | samtools sort - $bam_name 2> /dev/null";
    }

**add samtools sort -o option and Filename Extension:**
if($opt_q) {
        system "bowtie -f -v 1 --best -k 1 --norc -S $opt_n $opt_e 2> /dev/null | sed -e 's/SO:unsorted/SO:coordinate/' 2> /dev/null | samtools view -S -b -u - 2> /dev/null | samtools sort - **-o $bam_name.bam** 2> /dev/null";
    } else {
        system "bowtie -f -v 1 --best -k 1 --norc -S $opt_n $opt_e | sed -e 's/SO:unsorted/SO:coordinate/' | samtools view -S -b -u - 2> /dev/null | samtools sort - **-o $bam_name.bam** 2> /dev/null";
    }

**Comment by MikeAxtell** [comment]
Fixed as of version 4.4 and now 4.5
