### ISSUE TITLE
Transcriptome has to be the same for the degradome density file

### ISSUE THREAD

**Issue by juanmas07** [MikeAxtell/CleaveLand4#5]
I'm getting this but not sure why.

**FATAL: Transcriptome has to be the same for the degradome density file and the GSTAr alignment file**

This is the command I'm using:

`➜  git:(master) ✗ perl scripts/aux/CleaveLand4-4.4/CleaveLand4.pl  -u res/res-4dl/selected_miRNA.4dl.3.fasta -n data/cds/Triticum_aestivum.TGACv1.cds.all.fa -e data/degradome/sra_data.fasta -o plots/ -t -a -p 0.01 > cleaveland.4dl.3.out
`

**Comment by juanmas07** [comment]
These are the dependences versions:
```

Checking Dependencies
       	bowtie: PASS version 0.12.7
       	bowtie-build: PASS version 0.12.7
       	RNAplex: PASS RNAplex 2.3.3
       	GSTAr: PASS GSTAr.pl version 1.0
       	samtools: PASS Version: 1.3.1 (using htslib 1.3.1)
       	R: PASS R version 2.14.1 (2011-12-22)
```

**Comment by MikeAxtell** [comment]
Compare the gene names found in the degradome density file to those in
the GSTAR alignment file, and to the original gene names in your input
transcriptome file 'Triticum_aestivum.TGACv1.cds.all.fa'. I haven't
looked at CleaveLand4 code in a very long time, but I think it could
be that the script is sensitive to whitespaces and shell characters in
transcript names; that may be the source of the issue.

On Thu, Mar 23, 2017 at 8:12 AM, juanmas07 <notifications@github.com> wrote:
> These are the dependences versions:
>
> Checking Dependencies
>        	bowtie: PASS version 0.12.7
>        	bowtie-build: PASS version 0.12.7
>        	RNAplex: PASS RNAplex 2.3.3
>        	GSTAr: PASS GSTAr.pl version 1.0
>        	samtools: PASS Version: 1.3.1 (using htslib 1.3.1)
>        	R: PASS R version 2.14.1 (2011-12-22)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Michael J. Axtell, Ph.D.
Professor of Biology
Penn State University
http://sites.psu.edu/axtell

**Comment by juanmas07** [comment]
That is exactly what I've found, I'm running again. Thanks
