### ISSUE TITLE
Error of "check bowtie version"

### ISSUE THREAD

**Issue by a92932000** [MikeAxtell/CleaveLand4#8]
New version of bowtie returns strings which begain with "bowtie-align"
for example:
$ bowtie --version
bowtie-align version 1.2.1.1

Therefore,
the line 367 of script "$vline =~ /^**bowtie** version (\S+)/" should be changed to "$vline =~ /^**bowtie.*** version (\S+)/"

**Comment by MikeAxtell** [comment]
Fixed as of version 4.5. thanks for letting me know, and sorry for forgetting about this issue for so long.
